'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EposPersonal
    Public Property MandantNr As Short
    Public Property PersonalNr As Integer
    Public Property KurzName As String
    Public Property Nachname As String
    Public Property Vorname As String
    Public Property Strasse As String
    Public Property Land As String
    Public Property PLZ As String
    Public Property Ort As String
    Public Property Telefon As String
    Public Property Telefon2 As String
    Public Property Telefon3 As String
    Public Property Geburtstag As Nullable(Of Date)
    Public Property EintrittsDatum As Nullable(Of Date)
    Public Property AustrittsDatum As Nullable(Of Date)
    Public Property PersonalAusweisNr As String
    Public Property FuehrerscheinDatum As Nullable(Of Date)
    Public Property GabelstaplerSchein As Boolean
    Public Property KranfuehrerSchein As Boolean
    Public Property FachNr As Nullable(Of Short)
    Public Property PersonalArtNr As Short
    Public Property Monteur As Boolean
    Public Property LeistungsNr As Nullable(Of Integer)
    Public Property LeistungsNrUeberstunden As Nullable(Of Integer)
    Public Property LeistungsNrNachtstunden As Nullable(Of Integer)
    Public Property LeistungsNrSamstagszuschlag As Nullable(Of Integer)
    Public Property LeistungsNrSonntagszuschlag As Nullable(Of Integer)
    Public Property LeistungsNrFeiertagszuschlag As Nullable(Of Integer)
    Public Property LeistungsNrAusloeseStunden As Nullable(Of Integer)
    Public Property LeistungsNrAusloeseTag As Nullable(Of Integer)
    Public Property WerkstattWagenLeistungNr As Nullable(Of Integer)
    Public Property PkwLeistungNr As Nullable(Of Integer)
    Public Property AngelegtDatum As Date
    Public Property AngelegtUser As Short
    Public Property AenderungDatum As Nullable(Of Date)
    Public Property AenderungUser As Nullable(Of Short)
    Public Property EMail As String
    Public Property EMail2 As String
    Public Property FilialNr As Nullable(Of Integer)
    Public Property Bemerkung As String
    Public Property FuehrerscheinNr As String
    Public Property ReisepassNr As String
    Public Property PersonalBild As String
    Public Property PersonalBildName As String
    Public Property TagesSollStunden As Nullable(Of Decimal)
    Public Property MonatsSollStunden As Nullable(Of Decimal)
    Public Property AussendienstMitarbeiter As Boolean
    Public Property PersonalNrExport As String
    Public Property PersonalNrTankstelle As String
    Public Property SpesenLandNr As Nullable(Of Integer)
    Public Property PersonalArtNr2 As Nullable(Of Short)
    Public Property PersonalKommunikationsId As String
    Public Property PersonalKommunikationsId2 As String
    Public Property ZusatzFeld1 As String
    Public Property ZusatzFeld2 As String
    Public Property ZusatzFeld3 As String
    Public Property ZusatzFeld4 As String
    Public Property ZusatzFeld5 As String
    Public Property ZusatzFeld6 As String
    Public Property ZusatzFeld7 As String
    Public Property ZusatzFeld8 As String
    Public Property ZusatzFeld9 As String
    Public Property ZusatzFeld10 As String
    Public Property ZusatzFeldMemo1 As String
    Public Property ZusatzFeldMemo2 As String
    Public Property ZusatzFeldMemo3 As String
    Public Property ZusatzFeldNum1 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum2 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum3 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum4 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum5 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum6 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum7 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum8 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum9 As Nullable(Of Decimal)
    Public Property ZusatzFeldNum10 As Nullable(Of Decimal)
    Public Property ZusatzFeldFarbe1 As String
    Public Property ZusatzFeldFarbe2 As String
    Public Property ZusatzFeldFarbe3 As String
    Public Property ZusatzFeldDatum1 As Nullable(Of Date)
    Public Property ZusatzFeldDatum2 As Nullable(Of Date)
    Public Property ZusatzFeldDatum3 As Nullable(Of Date)
    Public Property ZusatzFeldDatum4 As Nullable(Of Date)
    Public Property ZusatzFeldDatum5 As Nullable(Of Date)
    Public Property FibuKennzeichen As String
    Public Property ArbeitsBerichteExport As Boolean
    Public Property FahrerKartenNr As String
    Public Property UeberstundenKontoVerwenden As Boolean
    Public Property UeberstundenKontoMaxStunden As Nullable(Of Decimal)
    Public Property OnlineVerfuegbar As Boolean
    Public Property ComplianceDatumAdresse As Nullable(Of Date)
    Public Property OnlineApplikationSupervisor As Boolean
    Public Property UeberstundenKontoNurZuschlagBezahlenBis As Nullable(Of Decimal)
    Public Property UrlaubsAnspruchTage As Nullable(Of Decimal)
    Public Property SageStdKST As Nullable(Of Integer)
    Public Property UserNr As Nullable(Of Short)
    Public Property MobileAppPersonalStunden As Boolean
    Public Property MobileAppKundenInfo As Boolean
    Public Property MobileAppAuftragsEingabe As Boolean
    Public Property MobileAppSystemTools As Boolean
    Public Property UeberstundenKontoAbStunden As Nullable(Of Decimal)
    Public Property DispoHinweisText As String
    Public Property MobileAppAuslieferung As Boolean
    Public Property MobileAppBilder As Boolean
    Public Property OnlineApplikationBesichtigung As Boolean
    Public Property VertreterNr As Nullable(Of Short)
    Public Property PersonalStundenArtNrArbeit As Nullable(Of Short)
    Public Property PersonalStundenArtNrPause As Nullable(Of Short)
    Public Property PersonalStundenArtNrWarten As Nullable(Of Short)
    Public Property OnlineLoginName As String
    Public Property AP_FahrerLogin As String
    Public Property Anrede As String
    Public Property ArbeitszeitAusSystemDaten As Boolean
    Public Property ArbeitszeitBeginn As Nullable(Of Date)
    Public Property ArbeitszeitEnde As Nullable(Of Date)
    Public Property ArbeitszeitBeginnMo As Nullable(Of Date)
    Public Property ArbeitszeitEndeMo As Nullable(Of Date)
    Public Property ArbeitszeitBeginnFr As Nullable(Of Date)
    Public Property ArbeitszeitEndeFr As Nullable(Of Date)
    Public Property UeberstundenBeginn As Nullable(Of Date)
    Public Property UeberstundenEnde As Nullable(Of Date)
    Public Property NachtstundenBeginn As Nullable(Of Date)
    Public Property NachtstundenEnde As Nullable(Of Date)
    Public Property Nachtstunden2Beginn As Nullable(Of Date)
    Public Property Nachtstunden2Ende As Nullable(Of Date)
    Public Property PausenBeginn As Nullable(Of Date)
    Public Property PausenDauer As Nullable(Of Decimal)
    Public Property OnlineApplikationPersonalTermine As Boolean
    Public Property CreationUser As String
    Public Property LastUpdateUser As String
    Public Property FirmenName As String

End Class
