'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace EloExplorer

    Partial Public Class FileIndex
        Public Property FileId As Integer
        Public Property IndexId As Integer
        Public Property IndexValue As String
        Public Property Creation As Date
        Public Property CreationUser As String
        Public Property LastUpdate As Nullable(Of Date)
        Public Property LastUpdateUser As String
        Public Property RowVersion As Integer
    
        Public Overridable Property TreeItemFile As TreeItemFile
        Public Overridable Property StIndex As StIndex
    
    End Class

End Namespace
